"""added new tables

Revision ID: e820b19e34c1
Revises: 2649d61b8cef
Create Date: 2026-05-04 22:39:18.906831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e820b19e34c1'
down_revision: Union[str, Sequence[str], None] = '2649d61b8cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['app_name'], ['apps.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['app_name'], ['apps.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('api_keys', sa.Column('app_id', sa.String(), nullable=True))
    op.drop_column('api_keys', 'tenant_id')
    op.drop_column('api_keys', 'user_id')
    op.add_column('grievances', sa.Column('audio_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'grievances', 'audios', ['audio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grievances', type_='foreignkey')
    op.drop_column('grievances', 'audio_id')
    op.add_column('api_keys', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('api_keys', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('api_keys', 'app_id')
    op.drop_table('categories')
    op.drop_table('audios')
    op.drop_table('apps')
    # ### end Alembic commands ###
